#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

payload="$(cat <&0)"

jq -n "{
  version: {ref: $(jq -r '.version.ref' <<<"$payload" | jq -R .)}
}" >&3
